# Generated by Django 4.0.5 on 2022-07-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.CharField(choices=[('F', 'Full Sun'), ('P', 'Partial Sun'), ('S', 'Shade')], default='F', max_length=1)),
                ('moisture', models.CharField(choices=[('D', 'Dry'), ('M', 'Medium'), ('W', 'Wet')], default='D', max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
