# Generated by Django 4.0.5 on 2022-07-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='plant',
        ),
    ]
